all:
  children:
    iscsi:
      hosts:

    jumpboxes_windows:
      hosts:

    jumpboxes_linux:
      hosts:
        10.96.1.4:
          ansible_connection:  "ssh"
          ansible_user:        "bdelangh"
        10.96.1.5:
          ansible_connection:  "ssh"
          ansible_user:        "bdelangh"

    hanadbnodes:
      hosts:
        10.97.1.10:
          ansible_connection:  "ssh"
          ansible_user:        "bdelangh"

    scs:
      hosts:
        10.97.3.10:
          ansible_connection: "ssh"
          ansible_user:       "bdelangh"

    app:
      hosts:
        10.97.3.14:
          ansible_connection: "ssh"
          ansible_user:       "bdelangh"
        10.97.3.15:
          ansible_connection: "ssh"
          ansible_user:       "bdelangh"
        10.97.3.16:
          ansible_connection: "ssh"
          ansible_user:       "bdelangh"

    web:
      hosts:
        10.97.3.24:
          ansible_connection: "ssh"
          ansible_user:       "bdelangh"

    # Groups below are collections of the above groups for easier reference
    all_jumpboxes:
      children:
        jumpboxes_windows:
        jumpboxes_linux:

    all_linux_servers:
      children:
        jumpboxes_linux:
        hanadbnodes:
        scs:
        app:

    # Localhost provisioning
    local:
      hosts:
        localhost:
          ansible_connection: "local"
          ansible_user:       "azureadm"
